services:
  # for development purposes
  tests: &tests
    build: .
    environment:
      - TEST_TENANT_ID
      - TEST_CLIENT_ID
      - TEST_CLIENT_SECRET
      - TEST_KEY_VAULT_URL
      - TEST_KEY_NAME
      - TEST_KEY_VERSION

  tests-local:
    <<: *tests
    volumes:
      - ./:/code

  ci:
    <<: *tests
    build:
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    volumes:
      - ./build/logs/:/code/build/logs/
