version: "3"
services:
  # for development purposes
  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_TENANT_ID
      - TEST_CLIENT_ID
      - TEST_CLIENT_SECRET
      - TEST_KEY_VAULT_URL
      - TEST_KEY_NAME
      - TEST_KEY_VERSION
      # For Codeclimate
      - CC_TEST_REPORTER_ID
      - GIT_BRANCH
      - GIT_COMMIT_SHA
    command: ["composer", "ci"]

  tests-local:
    <<: *tests
    volumes:
      - ./:/code

  ci:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/code/docker/tests-cc.sh"]
    volumes:
      - ./build/logs/:/code/build/logs/
